# Generated by Django 4.1.7 on 2023-03-18 00:41

import articles.models
import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to=articles.models.image_upload)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('article_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-article_date',),
            },
        ),
    ]
