# Generated by Django 4.1.5 on 2023-02-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='place_2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
