# Generated by Django 4.1.7 on 2023-03-06 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=255, unique=True),
        ),
    ]
