# Generated by Django 4.1.7 on 2023-03-11 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_slug_alter_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
