# Generated by Django 4.1.7 on 2023-03-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_course_date_lesson_lesson_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-course_date',)},
        ),
    ]
